server:
  port: 8081
spring:
  application:
    name: food-listing
  datasource:
  #    url: jdbc:h2:mem:cartdb
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password:
  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

application:
  greeting: Configuration updated! Hello from Listing Service is.
  feature-toggle: false # Change this to false  
  name: Hello form food listing page
      

